services:
  front:
    container_name: fac-report
    build:
      context:  "./"
    ports:
      - "3000:3000"
    volumes:
      - .:/app/front
      - /app/front/node_modules
    restart: always
    