
export const FONTSET_MAIN_MENU_TITLESIZE = "30px"
export const FONTSET_MAIN_MENU_VERSIONSIZE = "10px"
export const FONTSET_MAIN_MENU_SIZE = "13px"


export const FONTSET_DEFAULT_BUTTON_SIZE = "12px"
export const FONTSET_DEFAULT_LABEL_SIZE = "12px"
export const FONTSET_DEFAULT_INPUT_SIZE = "13px"
export const FONTSET_DEFAULT_SELECT_SIZE = "12px"
export const FONTSET_DEFAULT_OPTION_SIZE = "12px"
export const FONTSET_DEFAULT_DIV_SIZE = "12px"