

export const SERVER_URL = process.env.REACT_APP_SERVER_URL;
export const INIT_GENERAL_SETTING = process.env.REACT_APP_INIT_GENERAL_SETTING;
export const INIT_APPROVES_SETTING = process.env.REACT_APP_INIT_APPROVES_SETTING;
export const INIT_TAB_SETTING = process.env.REACT_APP_INIT_TAB_SETTING;

export const INIT_REPORT_TYPE1 = process.env.REACT_APP_INIT_REPORT_TYPE1;
export const INIT_REPORT_TYPE2 = process.env.REACT_APP_INIT_REPORT_TYPE2;
export const INIT_REPORT_TYPE3 = process.env.REACT_APP_INIT_REPORT_TYPE3;

export const INIT_REPORT_TYPE1_SUB1 = process.env.REACT_APP_INIT_REPORT_TYPE1_SUB1;
export const INIT_REPORT_TYPE1_SUB2   = process.env.REACT_APP_INIT_REPORT_TYPE1_SUB2;   
export const INIT_REPORT_TYPE2_SUB1 = process.env.REACT_APP_INIT_REPORT_TYPE2_SUB1;
export const INIT_REPORT_TYPE3_SUB1 = process.env.REACT_APP_INIT_REPORT_TYPE3_SUB1;

export const INIT_MAINTAB_COUNT = process.env.REACT_APP_INIT_MAINTAB_COUNT;
export const INIT_SUBTAB_COUNT = process.env.REACT_APP_INIT_SUBTAB_COUNT;
export const INIT_TAB_COUNT = process.env.REACT_APP_INIT_TAB_COUNT;

export const CONST_TABINFO_NAME = process.env.REACT_APP_CONST_TABINFO_NAME;
export const CONST_UNITGROUP_NAME = process.env.REACT_APP_CONST_UNITGROUP_NAME;

export const CONST_LANG = process.env.REACT_APP_CONST_LANG
